version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sorteo_db
      - DB_USER=usuario
      - DB_PASS=contraseña
      - SESSION_SECRET=clave_secreta_sesiones
      - UPLOAD_PATH=./public/uploads
      - N8N_WEBHOOK_URL=https://tun8n.com/webhook/ticket-validation
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - sorteo-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sorteo_db
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=contraseña
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sorteo-network

volumes:
  postgres_data:

networks:
  sorteo-network:
    driver: bridge